name: OpenLane Flow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: efabless/openlane:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure config.tcl exists
        run: |
          if [ ! -f designs/my_project/config.tcl ]; then
            cat > designs/my_project/config.tcl <<EOL
set ::env(DESIGN_NAME) my_project
set ::env(VERILOG_FILES) "\$::env(DESIGN_DIR)/src/*.v"
set ::env(CLOCK_PORT) "clk"
set ::env(CLOCK_PERIOD) "10"
EOL
          fi

      - name: Run OpenLane flow
        run: |
          cd /openlane
          ./flow.tcl \
            -design /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/designs/my_project \
            -tag run_$(date +%s) -overwrite

      - name: Collect OpenLane results
        run: |
          mkdir -p openlane_results
          cp -r designs/my_project/runs/*/results/* openlane_results/ || true

      - name: Upload results as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: openlane-results
          path: openlane_results
