name: OpenLane R2G Flow

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - ".github/workflows/openlane-r2g.yml"

jobs:
  openlane-r2g:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Pull OpenLane Docker image
        run: |
          docker pull efabless/openlane:latest

      - name: Run OpenLane R2G Flow
        run: |
          mkdir -p $PWD/work
          cp -r src $PWD/work/rtl
          docker run --rm \
            -v $PWD/work:/openlane/work \
            -e INPUT_DESIGN_NAME="$(ls $PWD/work/rtl | grep -m1 .*)" \
            efabless/openlane:latest \
            bash -c "
              cd /openlane
              ./flow.tcl -design /openlane/work/rtl
            "
        # Adjust INPUT_DESIGN_NAME and flow.tcl usage as per your repo design organization

      - name: Upload Results (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: openlane-results
          path: work/
