name: OpenLane Flow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: efabless/openlane:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run OpenLane flow
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"

          # detect design folder inside designs/
          DESIGN_NAME=$(find "$GITHUB_WORKSPACE/designs" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | head -n1)
          if [ -z "$DESIGN_NAME" ]; then
            echo "No design folder found inside designs/"
            exit 1
          fi
          echo "Detected design: $DESIGN_NAME"

          # copy the design into /openlane/designs (OpenLane expects this)
          mkdir -p /openlane/designs/$DESIGN_NAME
          cp -r "$GITHUB_WORKSPACE/designs/$DESIGN_NAME"/* /openlane/designs/$DESIGN_NAME/

          # if config.tcl missing, create one
          if [ ! -f /openlane/designs/$DESIGN_NAME/config.tcl ]; then
            cat > /openlane/designs/$DESIGN_NAME/config.tcl <<EOL
set ::env(DESIGN_NAME) $DESIGN_NAME
set ::env(VERILOG_FILES) "\$::env(DESIGN_DIR)/src/*.v"
set ::env(CLOCK_PORT) "clk"
set ::env(CLOCK_PERIOD) "10"
EOL
          fi

          echo "Running OpenLane flow..."
          cd /openlane
          ./flow.tcl -design /openlane/designs/$DESIGN_NAME -tag run_$(date +%s) -overwrite

          # copy results back to workspace so we can upload
          mkdir -p "$GITHUB_WORKSPACE/openlane_results"
          cp -r /openlane/designs/$DESIGN_NAME/runs/*/results/* "$GITHUB_WORKSPACE/openlane_results/" || true

      - name: Upload results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: openlane-results
          path: openlane_results
