name: OpenLane R2G Flow
on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - ".github/workflows/openlane-r2g.yml"

jobs:
  openlane-r2g:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        
      - name: Pull OpenLane Docker image
        run: |
          docker pull efabless/openlane:2023.07.19-1
          
      - name: Prepare design files
        run: |
          mkdir -p openlane_run/designs/my_design/src
          cp -r src/* openlane_run/designs/my_design/src/
          
      - name: Create OpenLane config
        run: |
          cat > openlane_run/designs/my_design/config.json << 'EOF'
          {
              "DESIGN_NAME": "my_design",
              "VERILOG_FILES": "dir::src/*.v",
              "CLOCK_PERIOD": 10,
              "CLOCK_PORT": "clk",
              "CLOCK_NET": "clk",
              "FP_SIZING": "absolute",
              "DIE_AREA": "0 0 100 100",
              "FP_PIN_ORDER_CFG": "dir::pin_order.cfg",
              "PL_BASIC_PLACEMENT": true,
              "PL_TARGET_DENSITY": 0.5,
              "GLB_RT_ADJUSTMENT": 0.1,
              "SYNTH_STRATEGY": "AREA 0"
          }
          EOF
          
      - name: Create pin order config (optional)
        run: |
          cat > openlane_run/designs/my_design/pin_order.cfg << 'EOF'
          #N
          clk
          rst_n
          
          #S
          
          #E
          
          #W
          EOF
          
      - name: Run OpenLane R2G Flow
        run: |
          docker run --rm \
            -v $PWD/openlane_run:/openlane/designs \
            -v $PWD/results:/openlane/designs/my_design/runs \
            efabless/openlane:2023.07.19-1 \
            sh -c "flow.tcl -design my_design -tag run_$(date +%Y_%m_%d_%H_%M_%S)"
            
      - name: Check results and create summary
        run: |
          if [ -d "results" ]; then
            echo "## OpenLane Flow Results" > results_summary.md
            echo "" >> results_summary.md
            
            # Find the latest run directory
            LATEST_RUN=$(ls -t results/ | head -n1)
            echo "Latest run: $LATEST_RUN" >> results_summary.md
            
            # Check if final GDS was generated
            if [ -f "results/$LATEST_RUN/final/gds/my_design.gds" ]; then
              echo "✅ GDSII generation: SUCCESS" >> results_summary.md
            else
              echo "❌ GDSII generation: FAILED" >> results_summary.md
            fi
            
            # Check if DEF was generated
            if [ -f "results/$LATEST_RUN/final/def/my_design.def" ]; then
              echo "✅ DEF generation: SUCCESS" >> results_summary.md
            else
              echo "❌ DEF generation: FAILED" >> results_summary.md
            fi
            
            # Add timing summary if available
            if [ -f "results/$LATEST_RUN/reports/final_summary_report.csv" ]; then
              echo "" >> results_summary.md
              echo "### Timing Summary" >> results_summary.md
              echo "\`\`\`" >> results_summary.md
              head -n 10 "results/$LATEST_RUN/reports/final_summary_report.csv" >> results_summary.md
              echo "\`\`\`" >> results_summary.md
            fi
            
            cat results_summary.md
          else
            echo "No results directory found - flow may have failed"
            exit 1
          fi
          
      - name: Upload OpenLane Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: openlane-results-${{ github.run_number }}
          path: |
            results/
            results_summary.md
            openlane_run/designs/my_design/config.json
          retention-days: 30
          
      - name: Upload Logs on Failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: openlane-logs-${{ github.run_number }}
          path: |
            results/*/logs/
          retention-days: 7
