name: OpenLane Flow

on: [push]

jobs:
  run-openlane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run OpenLane
        run: |
          docker run --rm -v ${{ github.workspace }}:/openlane \
            -e DESIGN=my_project \
            efabless/openlane:latest \
            ./flow.tcl -design my_project
